<?php

namespace StateOne\States;

use StateOne\Contracts\StateInterface;
use StateOne\Item\Microwave;

final class HeatingState implements StateInterface
{
    public function __construct(private Microwave $microwave)
    {

    }

    public function start(int $duration): bool
    {
        return false;
    }

    public function stop(): bool
    {
        $this->microwave->changeState(new IdleState($this->microwave));
        return true;
    }

    public function openDoor(): bool
    {
        return false;
    }
}